### ISSUE TITLE
Sonarqube fails loading with Groovy Sonar 1.6RC9

### ISSUE THREAD

**Issue by roded** [musketyr/docker-sonarqube#1]
Hi, 
I've experienced this issue with the following commit: 52a9fdf8a95aa0fb16836ee2afb92c55e0aba6c9
The sonarqube process fails to load due to the following exception:

> 2018.11.08 21:44:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile vbnet/Sonar way
> 2018.11.08 21:44:04 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile grvy/Sonar way
> 2018.11.08 21:44:04 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
> java.lang.NullPointerException: Value function can't return null
> 	at java.util.Objects.requireNonNull(Objects.java:228)
> 	at org.sonar.core.util.stream.MoreCollectors.lambda$uniqueIndex$9(MoreCollectors.java:254)
> 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.insertActiveRuleParams(BuiltInQProfileInsertImpl.java:168)
> 	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.insertActiveRule(BuiltInQProfileInsertImpl.java:156)
> 	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.lambda$create$0(BuiltInQProfileInsertImpl.java:86)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
> 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> 	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.create(BuiltInQProfileInsertImpl.java:87)
> 	at org.sonar.server.qualityprofile.RegisterQualityProfiles.create(RegisterQualityProfiles.java:119)
> 	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:89)
> 	at java.lang.Iterable.forEach(Iterable.java:75)
> 	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:86)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
> 	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
> 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
> 	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
> 	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
> 	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
> 	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
> 	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
> 	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
> 	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
> 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:46)
> 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:82)
> 	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:46)
> 	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:79)
> 	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
> 	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
> 	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
> 	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
> 	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
> 	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
> 	at java.lang.Thread.run(Thread.java:748)
> 2018.11.08 21:44:05 INFO  web[][o.s.p.StopWatcher] Stopping process
> 2018.11.08 21:44:08 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
> 2018.11.08 21:44:08 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
> 2018.11.08 21:44:08 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by musketyr** [comment]
Sorry, RC9 is broken. Last release of 7 should revert back to RC7.

Dne pá 9. lis 2018 12:09 uživatel roded <notifications@github.com> napsal:
